# For more things to flush this out, check out http://tldp.org/LDP/abs/html/sample-bashrc.html

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

platform='unknown'
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do #resolve $SOURCE until it is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

source $DIR/000.ls-default.sh

alias cls='reset'
alias quit='exit'

# Always copy recursively and with verbosity
alias cp='cp -rv'

# Always create the full path to a folder
alias mkdir='mkdir -pv'

LS_COLORS=$LS_COLORS:'di=1;36:' ; export LS_COLORS

# Set the 'history' command to show when the previous commands were executed
HISTTIMEFORMAT="[%F %T] "

# Append history across sessions
shopt -s histappend

# Verify that history can be appended, or recover if something goes wrong
shopt -s histreedit
shopt -s histverify

# Ignore history commands that start with whitespace or duplicate commands
HISTCONTROL='ignoreboth'

# Commit history for the window, clear history, and reload all history before showing the prompt
PROMPT_COMMAND="history -a;history -c;history -r; $PROMPT_COMMAND"

# Note: ~/.ssh/environment should not be used, as it already has a different purpose in SSH.
env=~/.ssh/agent.env

# Note: Don't bother checking SSH_AGENT_PID. It's not used by SSH itself, and it might even
# be incorrect (for example, when using agent-forwarding over SSH).

agent_is_running() {
    if [ "$SSH_AUTH_SOCK" ]; then
        # ssh-add returns:
        #   0 = agent running, has keys
        #   1 = agent running, no keys
        #   2 = agent not running
        ssh-add -l >/dev/null 2>&1 || [ $? -eq 1 ]
    else
        false
    fi
}

agent_has_keys() {
    ssh-add -l >/dev/null 2>&1
}

agent_load_env() {
    . "$env" >/dev/null
}

agent_start() {
    (umask 007; ssh-agent >"$env")
    . "$env" >/dev/null
}

if ! agent_is_running; then
    agent_load_env
fi

if ! agent_is_running; then
    agent_start
    ssh-add
elif ! agent_has_keys; then
    ssh-add
fi

unset env

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# Run twolfson/sexy-bash-prompt
. ~/.bash_prompt

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Alias from https://unix.stackexchange.com/a/351222
function git_move() {
    if [ x`git rev-parse --show-toplevel 2> /dev/null` = x ];
    then
        # not in a git repo, perform standard git_move
        mv "$@"
    else
        git mv "$@"
    fi
}

alias mv=git_move
